-- =============================
-- CATEGORIES
-- =============================
create table categories (
  id bigint generated by default as identity primary key,
  name varchar not null unique,
  description varchar
);

-- =============================
-- SUPPLIERS
-- =============================
create table suppliers (
  id bigint generated by default as identity primary key,
  name varchar not null,
  phone varchar,
  email varchar,
  address varchar
);

-- =============================
-- MEDICINES
-- =============================
create table medicines (
  id bigint generated by default as identity primary key,
  name varchar not null,
  generic_name varchar,
  category_id bigint references categories(id) on delete set null,
  supplier_id bigint references suppliers(id) on delete set null,
  requires_rx boolean default false,
  min_stock int default 10,
  description varchar
);

-- =============================
-- MEDICINE BATCHES
-- =============================
create table medicine_batches (
  id bigint generated by default as identity primary key,
  medicine_id bigint not null references medicines(id) on delete cascade,
  batch_code varchar not null unique,
  expiration_date date not null,
  quantity int not null check (quantity >= 0),
  unit_cost numeric(10,2),
  unit_price numeric(10,2) not null,
  created_at timestamp with time zone default now()
);

-- =============================
-- CUSTOMERS
-- =============================
create table customers (
  id bigint generated by default as identity primary key,
  name varchar not null,
  email varchar unique,
  phone varchar,
  address varchar,
  created_at timestamp with time zone default now()
);

-- =============================
-- SALES
-- =============================
create table sales (
  id bigint generated by default as identity primary key,
  customer_id bigint references customers(id) on delete set null,
  sale_date timestamp with time zone default now(),
  total numeric(10,2),
  status varchar default 'completed',
  notes varchar
);

-- =============================
-- SALE DETAILS
-- =============================
create table sale_details (
  id bigint generated by default as identity primary key,
  sale_id bigint references sales(id) on delete cascade,
  batch_id bigint references medicine_batches(id),
  quantity int not null check (quantity > 0),
  unit_price numeric(10,2) not null,
  subtotal numeric(10,2) not null
);

-- =============================
-- DELIVERY ZONES
-- =============================
create table delivery_zones (
  id bigint generated by default as identity primary key,
  zone_name varchar not null,
  coverage_area varchar,
  open_time time not null,
  close_time time not null,
  is_active boolean default true
);

-- =============================
-- DELIVERY ORDERS
-- =============================
create table delivery_orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references customers(id),
  zone_id bigint references delivery_zones(id),
  address varchar not null,
  order_date timestamp with time zone default now(),
  scheduled_time time,
  status varchar default 'pending',
  total numeric(10,2)
);

-- =============================
-- DELIVERY DETAILS
-- =============================
create table delivery_details (
  id bigint generated by default as identity primary key,
  order_id bigint references delivery_orders(id) on delete cascade,
  batch_id bigint references medicine_batches(id),
  quantity int not null check (quantity > 0),
  unit_price numeric(10,2) not null,
  subtotal numeric(10,2) not null
);

-- =============================
-- PRICE AUDIT
-- =============================
create table price_audit (
  id bigint generated by default as identity primary key,
  batch_id bigint references medicine_batches(id),
  old_price numeric(10,2),
  new_price numeric(10,2),
  changed_at timestamp with time zone default now(),
  changed_by varchar
);

-- =============================
-- STOCK MOVEMENTS
-- =============================
create table stock_movements (
  id bigint generated by default as identity primary key,
  batch_id bigint references medicine_batches(id),
  movement_type varchar,
  quantity int,
  reference_id bigint,
  moved_at timestamp with time zone default now()
);